$:
  tag_push:
    - runner:
        cpus: 4
      services:
        - docker
      docker:
        volumes:
          - /data/codewiki/${CNB_REPO_SLUG}:data
      stages:
        - name: Make Code Wiki
          timeout: 2h
          image: cnbcool/codewiki:latest
          settings:
            git_doc_dir: /data/codewiki/${CNB_REPO_SLUG}
  vscode:
    - runner:
        cpus: 8
        tags: cnb:arch:amd64
      docker:
        image: docker.cnb.cool/zishuo/default-dev-env:latest
      imports: https://cnb.cool/zishuo/system-env/-/blob/main/envs/init.yml
      env:
        GOBUILD_WELCOME_CMD: |
          init-ai-config
      services:
        - name: vscode
          options:
            keepAliveTimeout: 86400000
        - name: docker
          options:
            rootlessBuildkitd:
              enabled: true
      stages:
        - name: Restore AI Config
          script: |
            if [ -e "/root/.scripts/ai-cache.sh" ]; then
              bash /root/.scripts/ai-cache.sh restore
            fi
        - name: Install Tools or Plugins
          script: |
            if [ -e "${CNB_BUILD_WORKSPACE}/.scripts/install.sh" ]; then
              bash ${CNB_BUILD_WORKSPACE}/.scripts/install.sh
            fi
        - name: Wait for Vscode
          type: vscode:go
        - name: Claude Code Update
          script: |
            claude update
        - name: OpenAI Codex Update
          script: |
            bun install -g @openai/codex@latest
        - name: Install MCP Tools
          script: |
            bun install -g tdd-guard@latest
            bun install -g mcp-remote@latest
            bun install -g repomix@latest
            bun install -g open-websearch@latest
            bun install -g @fission-ai/openspec@latest
            bun install -g @modelcontextprotocol/server-sequential-thinking@latest
            bun install -g @modelcontextprotocol/server-memory@latest
            bun install -g @pimzino/spec-workflow-mcp@latest
            bun install -g @upstash/context7-mcp@latest
            setsid spec-workflow-mcp /workspace --no-open --dashboard --port=8888 2>&1 > /dev/null &
      endStages:
        - name: Save AI Config
          script: |
            if [ -e "/root/.scripts/ai-cache.sh" ]; then
              bash /root/.scripts/ai-cache.sh save
            fi
        - name: Send Notifications
          script: |
            if [ -e "${CNB_BUILD_WORKSPACE}/.scripts/notifications.sh" ]; then
              bash ${CNB_BUILD_WORKSPACE}/.scripts/notifications.sh
            fi
